version: "3"
services:
  mysql:
    image: mysql:5.7.21
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ''
      MYSQL_ALLOW_EMPTY_PASSWORD: 'true'
      MYSQL_USER: 'root'
networks:
  default:
    external:
      name: znet